export const getMovieList = {
    ON_CHANGE_SEARCH_INPUT: "ON_CHANGE_SEARCH_INPUT",
    SET_MOVIE_LIST: "SET_MOVIE_LIST",
    SET_LOADING_MOVIE_LIST: "SET_LOADING_MOVIE_LIST",
    SET_CURRENT_PAGE: "SET_CURRENT_PAGE"
}

export const getMovieDetail = {
    SET_MOVIE_DETAIL: "SET_MOVIE_DETAIL",
    SET_LOADING_MOVIE_DETAIL: "SET_LOADING_MOVIE_DETAIL"
}